<?php

use Illuminate\Database\Seeder;

class TownSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		//pirate towns, 9 towns, 3 colonies
		//1, jamaica
		DB::table('towns')->insert([
			'town_name' => 'Port Royal',
			'country' => '1',
			'colony' => '1',
			'xcoord' => '1889',
			'ycoord' => '1413',
			'foundation' => '1494',
			'category_size' => 'city',
			'population' => '6500',
			'guards' => '500',
			'fort' => 'Fort Charles',			
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'copper',
			'factory' => 'jewelry',
			'distillery' => 'rum'				
		]);
		//2, jamaica
		DB::table('towns')->insert([
			'town_name' => 'Montego Bay',
			'country' => '1',
			'colony' => '1',
			'xcoord' => '1790',
			'ycoord' => '1365',
			'foundation' => '1511',
			'category_size' => 'town',
			'population' => '4000',
			'guards' => '500',
			'fort' => 'Fort Montego',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'meat',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'leatherwork',
			'distillery' => 'rum'	
		]);	
		//3, cayman islands, jamaica
		DB::table('towns')->insert([
			'town_name' => 'Georgetown',
			'country' => '1',
			'colony' => '1',
			'xcoord' => '1487',
			'ycoord' => '1288',
			'foundation' => '1661',
			'category_size' => 'town',
			'population' => '1000',
			'guards' => '200',
			'fort' => 'Fort George',			
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'	
		]);
		//4, belize, honduras
		DB::table('towns')->insert([
			'town_name' => 'Belize',
			'country' => '1',
			'colony' => '2',
			'xcoord' => '892',
			'ycoord' => '1451',
			'foundation' => '1638',
			'category_size' => 'town',
			'population' => '1000',
			'guards' => '200',
			'fort' => 'Fort Barlee',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'wood',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//5, belize, honduras
		DB::table('towns')->insert([
			'town_name' => 'Bluefields',
			'country' => '1',
			'colony' => '2',
			'xcoord' => '892',
			'ycoord' => '1280',
			'foundation' => '1657',
			'category_size' => 'town',
			'population' => '400',
			'guards' => '80',
			'fort' => 'Fort Bay',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'wood',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'	
		]);
		//6, providence, honduras
		DB::table('towns')->insert([
			'town_name' => 'Providence',
			'country' => '1',
			'colony' => '2',
			'xcoord' => '1461',
			'ycoord' => '1901',
			'foundation' => '1632',
			'category_size' => 'town',
			'population' => '600',
			'guards' => '100',
			'fort' => 'Fort Bay',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'none'	
		]);		
		//7, yucatan, jamaica, belize, honduras
		DB::table('towns')->insert([
			'town_name' => 'Carmen',
			'country' => '1',
			'colony' => '2',
			'xcoord' => '573',
			'ycoord' => '1344',
			'foundation' => '1672',
			'category_size' => 'town',
			'population' => '1500',
			'guards' => '300',
			'fort' => 'Fort ',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'spices',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'	
		]);	
		//8, roatan, bay islands, belize, honduras
		DB::table('towns')->insert([
			'town_name' => 'Coxen Hole',
			'country' => '1',
			'colony' => '2',
			'xcoord' => '1035',
			'ycoord' => '1562',
			'foundation' => '1643',
			'category_size' => 'town',
			'population' => '500',
			'guards' => '80',
			'fort' => 'Fort Linwell',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'salt',
			'factory' => 'calico',
			'distillery' => 'rum'	
		]);			
		//9, tortuga, haiti, tortuga
		DB::table('towns')->insert([
			'town_name' => 'Tortuga',
			'country' => '1',
			'colony' => '3',
			'xcoord' => '2250',
			'ycoord' => '1221',
			'foundation' => '1625',
			'category_size' => 'town',
			'population' => '2500',
			'guards' => '400',
			'fort' => 'Fort de Rocher',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'pottery',
			'distillery' => 'none'
		]);
		//buccaneer towns, 2 towns, 1 colony
		//10, new providence, bahamas
		DB::table('towns')->insert([
			'town_name' => 'Nassau',
			'country' => '2',
			'colony' => '4',
			'xcoord' => '1844',
			'ycoord' => '739',
			'foundation' => '1670',
			'category_size' => 'town',
			'population' => '900',
			'guards' => '200',
			'fort' => 'Fort Montagu',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'none'
		]);	
		//11, eleuthera, bahamas
		DB::table('towns')->insert([
			'town_name' => 'Governors Harbour',
			'country' => '2',
			'colony' => '4',
			'xcoord' => '1938',
			'ycoord' => '727',
			'foundation' => '1648',
			'category_size' => 'town',
			'population' => '900',
			'guards' => '200',
			'fort' => 'Fort Charlotte',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'leatherwork',
			'distillery' => 'none'
		]);
		//dutch towns, 6 towns, 2 colonies
		//12, curacao, leeward
		DB::table('towns')->insert([
			'town_name' => 'Willemstad',
			'country' => '3',
			'colony' => '5',
			'xcoord' => '2582',
			'ycoord' => '1944',
			'foundation' => '1634',
			'category_size' => 'town',
			'population' => '5000',
			'guards' => '500',
			'fort' => 'Fort Amsterdam',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'none',
			'mining' => 'salt',
			'factory' => 'goods',
			'distillery' => 'none'
		]);	
		//13, aruba, leeward
		DB::table('towns')->insert([
			'town_name' => 'Oranjestad',
			'country' => '3',
			'colony' => '5',
			'xcoord' => '2485',
			'ycoord' => '1906',
			'foundation' => '1636',
			'category_size' => 'town',
			'population' => '3000',
			'guards' => '400',
			'fort' => 'Fort Zoutman',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'leatherwork',
			'distillery' => 'none'
		]);	
		//14, bonaire, leeward
		DB::table('towns')->insert([
			'town_name' => 'Playa',
			'country' => '3',
			'colony' => '5',
			'xcoord' => '2639',
			'ycoord' => '1939',
			'foundation' => '1639',
			'category_size' => 'town',
			'population' => '300',
			'guards' => '60',
			'fort' => 'Fort Oranje',			
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'none',
			'mining' => 'salt',
			'factory' => 'leatherwork',
			'distillery' => 'none'
		]);
		//15, st. eustatius, windward
		DB::table('towns')->insert([
			'town_name' => 'Oranjestad',
			'country' => '3',
			'colony' => '6',
			'xcoord' => '3105',
			'ycoord' => '1456',
			'foundation' => '1636',
			'category_size' => 'town',
			'population' => '300',
			'guards' => '60',
			'fort' => 'Fort Oranje',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//16, st. martin, windward
		DB::table('towns')->insert([
			'town_name' => 'Philipsburg',
			'country' => '3',
			'colony' => '6',
			'xcoord' => '3099',
			'ycoord' => '1405',
			'foundation' => '1631',
			'category_size' => 'town',
			'population' => '300',
			'guards' => '60',
			'fort' => 'Fort Willem',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'salt',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);
		//17, saba, windward
		DB::table('towns')->insert([
			'town_name' => 'De Botte',
			'country' => '3',
			'colony' => '6',
			'xcoord' => '3082',
			'ycoord' => '1442',
			'foundation' => '1640',
			'category_size' => 'village',
			'population' => '200',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);
		//english towns, 7 towns, 2	colonies		
		//18, antigua, leewards islands
		DB::table('towns')->insert([
			'town_name' => 'Saint Johns',
			'country' => '4',
			'colony' => '7',
			'xcoord' => '3204',
			'ycoord' => '1485',
			'foundation' => '1632',
			'category_size' => 'town',
			'population' => '3000',
			'guards' => '500',
			'fort' => 'Fort James',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'spices',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);	
		//19, barbuda, leewards islands
		DB::table('towns')->insert([
			'town_name' => 'Codrington',
			'country' => '4',
			'colony' => '7',
			'xcoord' => '3206',
			'ycoord' => '1445',
			'foundation' => '1667',
			'category_size' => 'village',
			'population' => '200',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);
		//20, anguilla, leewards islands
		DB::table('towns')->insert([
			'town_name' => 'The Valley',
			'country' => '4',
			'colony' => '7',
			'xcoord' => '3096',
			'ycoord' => '1386',
			'foundation' => '1667',
			'category_size' => 'village',
			'population' => '200',			
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'jewelry',
			'distillery' => 'rum'
		]);
		//21, turks and caicos islands, leewards islands
		DB::table('towns')->insert([
			'town_name' => 'Cockburn Town',
			'country' => '4',
			'colony' => '7',
			'xcoord' => '2387',
			'ycoord' => '1083',
			'foundation' => '1681',
			'category_size' => 'town',
			'population' => '900',
			'guards' => '200',
			'fort' => 'Fort George',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'salt',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);	
		//22, montserrat, leewards islands
		DB::table('towns')->insert([
			'town_name' => 'Plymouth',
			'country' => '4',
			'colony' => '7',
			'xcoord' => '3171',
			'ycoord' => '1527',
			'foundation' => '1632',
			'category_size' => 'town',
			'population' => '400',
			'guards' => '60',
			'fort' => 'Fort George',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);	
		//23, barbados, windward islands
		DB::table('towns')->insert([
			'town_name' => 'Bridgetown',
			'country' => '4',
			'colony' => '8',
			'xcoord' => '3399',
			'ycoord' => '1854',
			'foundation' => '1628',
			'category_size' => 'town',
			'population' => '5000',
			'guards' => '500',
			'fort' => 'Fort Charles',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'spices',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'indigo',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);	
		//24, grenada, windward islands
		DB::table('towns')->insert([
			'town_name' => 'Saint Georges',
			'country' => '4',
			'colony' => '8',
			'xcoord' => '3212',
			'ycoord' => '1949',
			'foundation' => '1650',
			'category_size' => 'town',
			'population' => '3500',
			'guards' => '500',
			'fort' => 'Fort Royal',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'spices',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//french towns, 7 towns, 2 colonies
		//25, martinique
		DB::table('towns')->insert([
			'town_name' => 'Saint Pierre',
			'country' => '5',
			'colony' => '9',
			'xcoord' => '3262',
			'ycoord' => '1704',
			'foundation' => '1638',
			'category_size' => 'town',
			'population' => '4000',
			'guards' => '500',
			'fort' => 'Fort de France',
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//26, guadeloupe
		DB::table('towns')->insert([
			'town_name' => 'Pointe a Pitre',
			'country' => '5',
			'colony' => '9',
			'xcoord' => '3232',
			'ycoord' => '1570',
			'foundation' => '1626',
			'category_size' => 'town',
			'population' => '3000',
			'guards' => '500',
			'fort' => 'Fort Fleur',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//27, marie galante, guadeloupe
		DB::table('towns')->insert([
			'town_name' => 'Grand Bourg',
			'country' => '5',
			'colony' => '9',
			'xcoord' => '3253',
			'ycoord' => '1591',
			'foundation' => '1653',
			'category_size' => 'town',
			'population' => '500',
			'guards' => '80',
			'fort' => 'Vieux Fort',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'indigo',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);
		//28, st. lucia
		DB::table('towns')->insert([
			'town_name' => 'Castries',
			'country' => '5',
			'colony' => '9',
			'xcoord' => '3279',
			'ycoord' => '1770',
			'foundation' => '1650',
			'category_size' => 'town',
			'population' => '3500',
			'guards' => '500',
			'fort' => 'Vieux Fort',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'pottery',
			'distillery' => 'rum'
		]);	
		//29, dominica
		DB::table('towns')->insert([
			'town_name' => 'Roseau',
			'country' => '5',
			'colony' => '9',
			'xcoord' => '3244',
			'ycoord' => '1655',
			'foundation' => '1660',
			'category_size' => 'town',
			'population' => '3000',
			'guards' => '500',
			'fort' => 'Fort Comfort',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'pottery',
			'distillery' => 'rum'
		]);	
		//30, haiti
		DB::table('towns')->insert([
			'town_name' => 'Port de Paix',
			'country' => '5',
			'colony' => '10',
			'xcoord' => '2238',
			'ycoord' => '1227',
			'foundation' => '1665',
			'category_size' => 'town',
			'population' => '4500',
			'guards' => '500',
			'fort' => 'Fort des Trois Pavillions',			
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'jewelry',
			'distillery' => 'rum'
		]);	
		//31, haiti
		DB::table('towns')->insert([
			'town_name' => 'Petit Goave',
			'country' => '5',
			'colony' => '10',
			'xcoord' => '2282',
			'ycoord' => '1355',
			'foundation' => '1663',
			'category_size' => 'town',
			'population' => '1200',
			'guards' => '200',
			'fort' => 'Fort Jacques',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);			
		//spanish towns, 26 towns, 7 colonies
		//32, hispaniola
		DB::table('towns')->insert([
			'town_name' => 'Santo Domingo',
			'country' => '6',
			'colony' => '11',
			'xcoord' => '2494',
			'ycoord' => '1365',
			'foundation' => '1496',
			'category_size' => 'city',
			'population' => '6500',
			'guards' => '500',
			'fort' => 'Fort Ozama',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//33, hispaniola
		DB::table('towns')->insert([
			'town_name' => 'Puerto Plata',
			'country' => '6',
			'colony' => '11',
			'xcoord' => '2425',
			'ycoord' => '1240',
			'foundation' => '1496',
			'category_size' => 'town',
			'population' => '2500',
			'guards' => '400',
			'fort' => 'Fort Felipe',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);	
		//34, puerto rico
		DB::table('towns')->insert([
			'town_name' => 'San Juan',
			'country' => '6',
			'colony' => '12',
			'xcoord' => '2828',
			'ycoord' => '1366',
			'foundation' => '1493',
			'category_size' => 'city',
			'population' => '6500',
			'guards' => '500',
			'fort' => 'Fort Segarra',			
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//35, puerto rico
		DB::table('towns')->insert([
			'town_name' => 'Ponce',
			'country' => '6',
			'colony' => '12',
			'xcoord' => '2782',
			'ycoord' => '1409',
			'foundation' => '1670',
			'category_size' => 'village',
			'population' => '200',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'textiles',
			'mining' => 'copper',
			'factory' => 'leatherwork',
			'distillery' => 'rum'
		]);	
		//36, cuba
		DB::table('towns')->insert([
			'town_name' => 'Havana',
			'country' => '6',
			'colony' => '13',
			'xcoord' => '1399',
			'ycoord' => '924',
			'foundation' => '1519',
			'category_size' => 'city',
			'population' => '6500',
			'guards' => '500',
			'fort' => 'Fort de los Tres Reyes',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'wood',
			'mining' => 'copper',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//37, cuba
		DB::table('towns')->insert([
			'town_name' => 'Santiago de Cuba',
			'country' => '6',
			'colony' => '13',
			'xcoord' => '1976',
			'ycoord' => '1225',
			'foundation' => '1515',
			'category_size' => 'town',
			'population' => '4000',
			'guards' => '500',
			'fort' => 'Fort Real',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'copper',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//38, cuba
		DB::table('towns')->insert([
			'town_name' => 'Baracoa',
			'country' => '6',
			'colony' => '13',
			'xcoord' => '2094',
			'ycoord' => '1189',
			'foundation' => '1511',
			'category_size' => 'town',
			'population' => '4000',
			'guards' => '500',
			'fort' => 'Fort Real',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//39, florida, cuba
		DB::table('towns')->insert([
			'town_name' => 'Saint Augustine',
			'country' => '6',
			'colony' => '13',
			'xcoord' => '1498',
			'ycoord' => '263',
			'foundation' => '1565',
			'category_size' => 'town',
			'population' => '1200',
			'guards' => '200',
			'fort' => 'Fort Caroline',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'wood',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'
		]);	
		//40, florida, cuba
		DB::table('towns')->insert([
			'town_name' => 'Pensacola',
			'country' => '6',
			'colony' => '13',
			'xcoord' => '975',
			'ycoord' => '209',
			'foundation' => '1559',
			'category_size' => 'town',
			'population' => '1500',
			'guards' => '300',
			'fort' => 'Fort George',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'none'
		]);	
		//41, mexico
		DB::table('towns')->insert([
			'town_name' => 'Veracruz',
			'country' => '6',
			'colony' => '14',
			'xcoord' => '195',
			'ycoord' => '1294',
			'foundation' => '1519',
			'category_size' => 'city',
			'population' => '6500',
			'guards' => '500',
			'fort' => 'Fort Juan',
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'wood',
			'mining' => 'silver',
			'factory' => 'pottery',
			'distillery' => 'rum'
		]);	
		//42, mexico
		DB::table('towns')->insert([
			'town_name' => 'Tampico',
			'country' => '6',
			'colony' => '14',
			'xcoord' => '49',
			'ycoord' => '1007',
			'foundation' => '1532',
			'category_size' => 'village',
			'population' => '200',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'none',
			'mining' => 'silver',
			'factory' => 'leatherwork',
			'distillery' => 'none'
		]);	
		//43, yucatan
		DB::table('towns')->insert([
			'town_name' => 'Campeche',
			'country' => '6',
			'colony' => '15',
			'xcoord' => '684',
			'ycoord' => '1234',
			'foundation' => '1526',
			'category_size' => 'town',
			'population' => '2500',
			'guards' => '300',
			'fort' => 'Fort Miguel',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'spices',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'salt',
			'factory' => 'pottery',
			'distillery' => 'none'
		]);		
		//44, guatemala
		DB::table('towns')->insert([
			'town_name' => 'Trujillo',
			'country' => '6',
			'colony' => '16',
			'xcoord' => '1087',
			'ycoord' => '1599',
			'foundation' => '1524',
			'category_size' => 'town',
			'population' => '3000',
			'guards' => '500',
			'fort' => 'Fort Barbara',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'meat',
			'mill' => 'wood',
			'mining' => 'none',
			'factory' => 'leatherwork',
			'distillery' => 'none'
		]);	
		//45, guatemala
		DB::table('towns')->insert([
			'town_name' => 'Omoa',
			'country' => '6',
			'colony' => '16',
			'xcoord' => '907',
			'ycoord' => '1611',
			'foundation' => '1536',
			'category_size' => 'town',
			'population' => '1000',
			'guards' => '200',
			'fort' => 'Fort Fernando',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'meat',
			'mill' => 'wood',
			'mining' => 'none',
			'factory' => 'leatherwork',
			'distillery' => 'none'
		]);	
		//46, guatemala
		DB::table('towns')->insert([
			'town_name' => 'Puerto Limon',
			'country' => '6',
			'colony' => '16',
			'xcoord' => '1364',
			'ycoord' => '2155',
			'foundation' => '1569',
			'category_size' => 'town',
			'population' => '1000',
			'guards' => '200',
			'fort' => 'Fort Real',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'indigo',
			'farming' => 'meat',
			'mill' => 'wood',
			'mining' => 'none',
			'factory' => 'leatherwork',
			'distillery' => 'none'
		]);	
		//47, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Cartagena',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '1999',
			'ycoord' => '2094',
			'foundation' => '1533',
			'category_size' => 'city',
			'population' => '6500',
			'guards' => '500',
			'fort' => 'Fort Real',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'silver',
			'factory' => 'jewelry',
			'distillery' => 'none'
		]);	
		//48, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Puerto Bello',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '1640',
			'ycoord' => '2172',
			'foundation' => '1597',
			'category_size' => 'town',
			'population' => '900',
			'guards' => '200',
			'fort' => 'Fort Lorenzo',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'silver',
			'factory' => 'goods',
			'distillery' => 'none'
		]);	
		//49, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Nombre de Dios',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '1733',
			'ycoord' => '2184',
			'foundation' => '1540',
			'category_size' => 'town',
			'population' => '1000',
			'guards' => '200',
			'fort' => 'Fort Real',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'silver',
			'factory' => 'goods',
			'distillery' => 'none'
		]);
		//50, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Santa Marta',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '2117',
			'ycoord' => '2020',
			'foundation' => '1525',
			'category_size' => 'town',
			'population' => '4000',
			'guards' => '500',
			'fort' => 'Fort Real',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'
		]);	
		//51, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Rio de la Hacha',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '2231',
			'ycoord' => '1992',
			'foundation' => '1535',
			'category_size' => 'town',
			'population' => '2000',
			'guards' => '300',
			'fort' => 'Fort Real',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'meat',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'leatherwork',
			'distillery' => 'none'
		]);
		//52, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Maracaibo',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '2344',
			'ycoord' => '2064',
			'foundation' => '1529',
			'category_size' => 'town',
			'population' => '5000',
			'guards' => '500',
			'fort' => 'Fort Real',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'coffee',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'
		]);	
		//53, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Puerto Cabello',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '2659',
			'ycoord' => '2088',
			'foundation' => '1578',
			'category_size' => 'town',
			'population' => '2000',
			'guards' => '300',
			'fort' => 'Fort Real',
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'jewelry',
			'distillery' => 'none'
		]);	
		//54, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Caracas',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '2751',
			'ycoord' => '2077',
			'foundation' => '1567',
			'category_size' => 'city',
			'population' => '6500',
			'guards' => '500',
			'fort' => 'Fort Real',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'
		]);
		//55, venezuela, new granada
		DB::table('towns')->insert([
			'town_name' => 'Cumana',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '2997',
			'ycoord' => '2090',
			'foundation' => '1515',
			'category_size' => 'town',
			'population' => '4000',
			'guards' => '500',
			'fort' => 'Fort Real',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);			
		//56, margarita, new granada
		DB::table('towns')->insert([
			'town_name' => 'Porlamar',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '3027',
			'ycoord' => '2047',
			'foundation' => '1536',
			'category_size' => 'town',
			'population' => '5000',
			'guards' => '500',
			'fort' => 'Fort Real',		
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'
		]);	
		//57, trinidad, new granada
		DB::table('towns')->insert([
			'town_name' => 'Port au Spain',
			'country' => '6',
			'colony' => '17',
			'xcoord' => '3233',
			'ycoord' => '2074',
			'foundation' => '1560',
			'category_size' => 'town',
			'population' => '3500',
			'guards' => '500',
			'fort' => 'Fort George',	
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'
		]);			
		//danish towns, 3 towns, 1 colony
		//58, charlotte amelie, st. thomas, virgin islands
		DB::table('towns')->insert([
			'town_name' => 'Taphus',
			'country' => '7',
			'colony' => '18',
			'xcoord' => '2933',
			'ycoord' => '1376',
			'foundation' => '1666',
			'category_size' => 'town',
			'population' => '1800',
			'guards' => '300',
			'fort' => 'Fort Christian',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//59, st. john, virgin islands
		DB::table('towns')->insert([
			'town_name' => 'Cruz Bay',
			'country' => '7',
			'colony' => '18',
			'xcoord' => '2946',
			'ycoord' => '1377',
			'foundation' => '1673',
			'category_size' => 'village',
			'population' => '200',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);	
		//60, st. john, virgin islands
		DB::table('towns')->insert([
			'town_name' => 'Coral Bay',
			'country' => '7',
			'colony' => '18',
			'xcoord' => '2954',
			'ycoord' => '1375',
			'foundation' => '1673',
			'category_size' => 'town',
			'population' => '300',
			'guards' => '80',
			'fort' => 'Fort Frederik',		
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);	
		//curonian towns, 1 town, 1 colony
		//61, tobago, new courland
		DB::table('towns')->insert([
			'town_name' => 'Jacobsstadt',
			'country' => '8',
			'colony' => '19',
			'xcoord' => '3305',
			'ycoord' => '2024',
			'foundation' => '1658',
			'category_size' => 'town',
			'population' => '500',
			'guards' => '150',
			'fort' => 'Fort Jacobus',			
			'sugarcane_plantation' => 'none',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fuits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'none'
		]);	
		//hospitaller towns, 3 towns, 1 colony
		//62, st. kitts
		DB::table('towns')->insert([
			'town_name' => 'Basseterre',
			'country' => '9',
			'colony' => '20',
			'xcoord' => '3125',
			'ycoord' => '1472',
			'foundation' => '1639',
			'category_size' => 'town',
			'population' => '1500',
			'guards' => '300',
			'fort' => 'Fort Charles',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'tobacco',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'pottery',
			'distillery' => 'rum'
		]);	
		//63, st. barths
		DB::table('towns')->insert([
			'town_name' => 'Carenage',
			'country' => '9',
			'colony' => '20',
			'xcoord' => '3117',
			'ycoord' => '1415',
			'foundation' => '1648',
			'category_size' => 'town',
			'population' => '900',
			'guards' => '200',
			'fort' => 'Fort Oscar',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'cocoa',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'none',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'none',
			'mining' => 'none',
			'factory' => 'goods',
			'distillery' => 'rum'
		]);	
		//64, st. croix, virgin islands
		DB::table('towns')->insert([
			'town_name' => 'Saint Croix',
			'country' => '9',
			'colony' => '20',
			'xcoord' => '2948',
			'ycoord' => '1434',
			'foundation' => '1695',
			'category_size' => 'village',
			'population' => '200',	
			'sugarcane_plantation' => 'sugarcane',
			'spices_plantation' => 'none',
			'cocoa_plantation' => 'none',
			'tobacco_plantation' => 'none',
			'coffee_plantation' => 'none',
			'cotton_plantation' => 'cotton',
			'dyes_plantation' => 'none',
			'farming' => 'fruits',
			'mill' => 'textiles',
			'mining' => 'none',
			'factory' => 'calico',
			'distillery' => 'rum'
		]);			
		
    }
}
